# PPD dos dados para treinamento, validação e teste

In [1]:
##importando bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import random
from numpy import median, mean
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import LocalOutlierFactor
from sklearn.covariance import EllipticEnvelope
from sklearn.ensemble import IsolationForest

* Outlier =  1 normal
* Outlier = -1 anormal

## IMPORTANDO dados treinamento, validacao e teste

In [2]:
# atributo DURACAO

In [3]:
## importando dataset TREINAMENTO
df_dur_trein = pd.read_csv('dataseteh/pp4/eh-dur-trein126.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_dur_trein.shape)
df_dur_trein.head()

(126, 9)

,dia,dia_semana,fim_semana,cclothes,eating,mcoffe,mhotfood,toileting,whandface
0,1,0,0,1319.0,4407.0,1600.0,2684.0,2840.0,2971.0
1,2,1,0,1242.0,7409.0,2122.0,4710.0,1937.0,2659.0
2,3,2,0,1513.0,3845.0,1157.0,6173.0,2800.0,2359.0
3,4,3,0,959.0,7010.0,1400.0,5820.0,2401.0,2862.0
4,5,4,0,947.0,8027.0,846.0,5823.0,1429.0,1066.0

In [4]:
## importando dataset VALIDACAO
df_dur_valid = pd.read_csv('dataseteh/pp4/eh-dur-valid70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_dur_valid.shape)
df_dur_valid.head()

(70, 17)

,dia,dia_semana,fim_semana,cclothes,eating,mcoffe,mhotfood,toileting,whandface,var_cclothes,var_eating,var_mcoffe,var_mhotfood,var_toileting,var_whandface,outlier,variacao
0,1,0,0,1017.0,3913.0,890.0,5447.0,2480.0,1558.0,1,1,1,1,1,1,1,0
1,2,1,0,944.0,8073.0,1666.0,2334.0,2203.0,2136.0,1,1,1,1,1,1,1,0
2,3,2,0,1470.0,5348.0,576.0,2430.0,1038.0,1756.0,1,1,1,1,1,1,1,0
3,4,3,0,1335.0,3903.0,1630.0,3026.0,2958.0,2857.0,1,1,1,1,1,1,1,0
4,5,4,0,708.0,8166.0,1353.0,5338.0,2522.0,2391.0,1,1,1,1,1,1,1,0

In [5]:
## importando dataset de TESTE
df_dur_test2035 = pd.read_csv('dataseteh/pp4/eh-dur-var20-35-test70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_dur_test2035.shape)
df_dur_test2035.head()

df_dur_test4055 = pd.read_csv('dataseteh/pp4/eh-dur-var40-55-test70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_dur_test4055.shape)
df_dur_test4055.head()

df_dur_test6075 = pd.read_csv('dataseteh/pp4/eh-dur-var60-75-test70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_dur_test6075.shape)
df_dur_test6075.head()

df_dur_test8095 = pd.read_csv('dataseteh/pp4/eh-dur-var80-95-test70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_dur_test8095.shape)
df_dur_test8095.head()

df_dur_test2095 = pd.read_csv('dataseteh/pp4/eh-dur-var20-95-test70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_dur_test2095.shape)
df_dur_test2095.head()

(70, 17)
(70, 17)
(70, 17)
(70, 17)
(70, 17)

,dia,dia_semana,fim_semana,cclothes,eating,mcoffe,mhotfood,toileting,whandface,var_cclothes,var_eating,var_mcoffe,var_mhotfood,var_toileting,var_whandface,outlier,variacao
0,1,0,0,1352.0,3913.0,890.0,7244.0,2480.0,2072.0,-1,1,1,-1,1,-1,-1,20-95
1,2,1,0,944.0,12674.0,1666.0,3664.0,947.0,918.0,1,-1,1,-1,-1,-1,-1,20-95
2,3,2,0,2631.0,5348.0,1031.0,2430.0,217.0,1756.0,-1,1,-1,1,-1,1,-1,20-95
3,4,3,0,1335.0,6244.0,652.0,4841.0,1183.0,1142.0,1,-1,-1,-1,-1,-1,-1,20-95
4,5,4,0,1005.0,11595.0,784.0,7579.0,1462.0,3395.0,-1,-1,-1,-1,-1,-1,-1,20-95

In [6]:
# atributo FREQUENCIA

In [7]:
## importando dataset TREINAMENTO
df_freq_trein = pd.read_csv('dataseteh/pp4/eh-freq-trein126.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_freq_trein.shape)
df_freq_trein.head()

(126, 9)

,dia,dia_semana,fim_semana,cclothes,eating,mcoffe,mhotfood,toileting,whandface
0,1,0,0,3.0,2.0,4.0,1.0,6.0,10.0
1,2,1,0,3.0,3.0,5.0,2.0,4.0,10.0
2,3,2,0,3.0,2.0,3.0,2.0,7.0,8.0
3,4,3,0,2.0,3.0,3.0,2.0,5.0,11.0
4,5,4,0,2.0,3.0,2.0,2.0,3.0,4.0

In [8]:
## importando dataset de TESTE
df_freq_test2035 = pd.read_csv('dataseteh/pp4/eh-freq-var20-35-test70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_freq_test2035.shape)
df_freq_test2035.head()

df_freq_test4055 = pd.read_csv('dataseteh/pp4/eh-freq-var40-55-test70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_freq_test4055.shape)
df_freq_test4055.head()

df_freq_test6075 = pd.read_csv('dataseteh/pp4/eh-freq-var60-75-test70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_freq_test6075.shape)
df_freq_test6075.head()

df_freq_test8095 = pd.read_csv('dataseteh/pp4/eh-freq-var80-95-test70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_freq_test8095.shape)
df_freq_test8095.head()

df_freq_test2095 = pd.read_csv('dataseteh/pp4/eh-freq-var20-95-test70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_freq_test2095.shape)
df_freq_test2095.head()

(70, 17)
(70, 17)
(70, 17)
(70, 17)
(70, 17)

,dia,dia_semana,fim_semana,cclothes,eating,mcoffe,mhotfood,toileting,whandface,var_cclothes,var_eating,var_mcoffe,var_mhotfood,var_toileting,var_whandface,outlier,variacao
0,1,0,0,7.0,2.0,2.0,7.0,6.0,8.0,-1,1,1,-1,1,-1,-1,20-95
1,2,1,0,2.0,5.0,4.0,6.0,11.0,16.0,1,-1,1,-1,-1,-1,-1,20-95
2,3,2,0,4.0,2.0,6.0,1.0,9.0,8.0,-1,1,-1,1,-1,1,-1,20-95
3,4,3,0,3.0,6.0,8.0,6.0,15.0,21.0,1,-1,-1,-1,-1,-1,-1,20-95
4,5,4,0,7.0,5.0,8.0,7.0,12.0,9.0,-1,-1,-1,-1,-1,-1,-1,20-95

In [9]:
# atributo DFREQ

In [10]:
## importando dataset TREINAMENTO
df_dfreq_trein = pd.read_csv('dataseteh/pp4/eh-dfreq-trein126.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_dfreq_trein.shape)
df_dfreq_trein.head()

(126, 9)

,dia,dia_semana,fim_semana,cclothes,eating,mcoffe,mhotfood,toileting,whandface
0,1,0,0,439.666667,2203.500000,400.000000,2684.0,473.333333,297.100000
1,2,1,0,414.000000,2469.666667,424.400000,2355.0,484.250000,265.900000
2,3,2,0,504.333333,1922.500000,385.666667,3086.5,400.000000,294.875000
3,4,3,0,479.500000,2336.666667,466.666667,2910.0,480.200000,260.181818
4,5,4,0,473.500000,2675.666667,423.000000,2911.5,476.333333,266.500000

In [11]:
## importando dataset de TESTE
df_dfreq_test2035 = pd.read_csv('dataseteh/pp4/eh-dfreq-var20-35-test70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_dfreq_test2035.shape)
df_dfreq_test2035.head()

df_dfreq_test4055 = pd.read_csv('dataseteh/pp4/eh-dfreq-var40-55-test70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_dfreq_test4055.shape)
df_dfreq_test4055.head()

df_dfreq_test6075 = pd.read_csv('dataseteh/pp4/eh-dfreq-var60-75-test70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_dfreq_test6075.shape)
df_dfreq_test6075.head()

df_dfreq_test8095 = pd.read_csv('dataseteh/pp4/eh-dfreq-var80-95-test70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_dfreq_test8095.shape)
df_dfreq_test8095.head()

df_dfreq_test2095 = pd.read_csv('dataseteh/pp4/eh-dfreq-var20-95-test70.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_dfreq_test2095.shape)
df_dfreq_test2095.head()

(70, 17)
(70, 17)
(70, 17)
(70, 17)
(70, 17)

,dia,dia_semana,fim_semana,cclothes,eating,mcoffe,mhotfood,toileting,whandface,var_cclothes,var_eating,var_mcoffe,var_mhotfood,var_toileting,var_whandface,outlier,variacao
0,1,0,0,193.0,1956.5,445.0,1034.0,413.333333,259.0,-1,1,1,-1,1,-1,-1,0
1,2,1,0,472.0,2534.0,416.5,610.0,86.000000,57.0,1,-1,1,-1,-1,-1,-1,0
2,3,2,0,657.0,2674.0,171.0,2430.0,24.000000,219.5,-1,1,-1,1,-1,1,-1,0
3,4,3,0,445.0,1040.0,81.0,806.0,78.000000,54.0,1,-1,-1,-1,-1,-1,-1,0
4,5,4,0,143.0,2319.0,98.0,1082.0,121.000000,377.0,-1,-1,-1,-1,-1,-1,-1,0

## Treinando MODELOS (4) para SEMANAS (18) para DURACAO

In [12]:
# inicializando listas para armazenar as métricas

for k in range (1,6): #iterando variacoes
    for z in range (1,4): #iterando atributos
        for y in range (1,5): #iteracao modelos

            csemana = []
            cvariacao = []
            cvp = []
            cvn = []
            cfp = []
            cfn = []
            cacuracia = []
            cprecisao = []
            csensibilidade = []
            cf1escore = []

            for x in range(1,19): #iterando semanas
                semana = x
                # ATRIBUTO DURACAO
                if (z == 1) & (k == 1): #duracao 20-35
                    df_test  = df_dur_test2035.iloc[:, [3,4,5,6,7]].copy()
                    df_dur_test = df_dur_test2035.copy()
                    df_trein = df_dur_trein.iloc[0:semana*7].copy()
                    df_trein = df_trein.iloc[:, [3,4,5,6,7]]
                    atributo = 'duracao'
                    variacao = '20-35'
                if (z == 1) & (k == 2): #duracao 40-55
                    df_test  = df_dur_test4055.iloc[:, [3,4,5,6,7]].copy()
                    df_dur_test = df_dur_test4055.copy()
                    df_trein = df_dur_trein.iloc[0:semana*7].copy()
                    df_trein = df_trein.iloc[:, [3,4,5,6,7]]
                    atributo = 'duracao'
                    variacao = '40-55'
                if (z == 1) & (k == 3): #duracao 60-75
                    df_test  = df_dur_test6075.iloc[:, [3,4,5,6,7]].copy()
                    df_dur_test = df_dur_test6075.copy()
                    df_trein = df_dur_trein.iloc[0:semana*7].copy()
                    df_trein = df_trein.iloc[:, [3,4,5,6,7]]
                    atributo = 'duracao'
                    variacao = '60-75'
                if (z == 1) & (k == 4): #duracao 80-95
                    df_test  = df_dur_test8095.iloc[:, [3,4,5,6,7]].copy()
                    df_dur_test = df_dur_test8095.copy()
                    df_trein = df_dur_trein.iloc[0:semana*7].copy()
                    df_trein = df_trein.iloc[:, [3,4,5,6,7]]
                    atributo = 'duracao'
                    variacao = '80-95'      
                if (z == 1) & (k == 5): #duracao 20-95
                    df_test  = df_dur_test2095.iloc[:, [3,4,5,6,7]].copy()
                    df_dur_test = df_dur_test2095.copy()
                    df_trein = df_dur_trein.iloc[0:semana*7].copy()
                    df_trein = df_trein.iloc[:, [3,4,5,6,7]]
                    atributo = 'duracao'
                    variacao = '20-95'                    
                    
                # ATRIBUTO FREQUENCIA
                if (z == 2) & (k == 1): #freq 20-35
                    df_test  = df_freq_test2035.iloc[:, [3,4,5,6,7]].copy()
                    df_freq_test = df_freq_test2035.copy()
                    df_trein = df_freq_trein.iloc[0:semana*7].copy()
                    df_trein = df_trein.iloc[:, [3,4,5,6,7]]
                    atributo = 'frequencia'
                    variacao = '20-35'
                if (z == 2) & (k == 2): #duracao 40-55
                    df_test  = df_freq_test4055.iloc[:, [3,4,5,6,7]].copy()
                    df_freq_test = df_freq_test4055.copy()
                    df_trein = df_freq_trein.iloc[0:semana*7].copy()
                    df_trein = df_trein.iloc[:, [3,4,5,6,7]]
                    atributo = 'frequencia'
                    variacao = '40-55'
                if (z == 2) & (k == 3): #duracao 60-75
                    df_test  = df_freq_test6075.iloc[:, [3,4,5,6,7]].copy()
                    df_freq_test = df_freq_test6075.copy()
                    df_trein = df_freq_trein.iloc[0:semana*7].copy()
                    df_trein = df_trein.iloc[:, [3,4,5,6,7]]
                    atributo = 'frequencia'
                    variacao = '60-75'
                if (z == 2) & (k == 4): #duracao 80-95
                    df_test  = df_freq_test8095.iloc[:, [3,4,5,6,7]].copy()
                    df_freq_test = df_freq_test8095.copy()
                    df_trein = df_freq_trein.iloc[0:semana*7].copy()
                    df_trein = df_trein.iloc[:, [3,4,5,6,7]]
                    atributo = 'frequencia'
                    variacao = '80-95'      
                if (z == 2) & (k == 5): #duracao 20-95
                    df_test  = df_freq_test2095.iloc[:, [3,4,5,6,7]].copy()
                    df_freq_test = df_freq_test2095.copy()
                    df_trein = df_freq_trein.iloc[0:semana*7].copy()
                    df_trein = df_trein.iloc[:, [3,4,5,6,7]]
                    atributo = 'frequencia'
                    variacao = '20-95'                     
                    
                # ATRIBUTO DFREQ
                if (z == 3) & (k == 1): #dfreq 20-35
                    df_test  = df_dfreq_test2035.iloc[:, [3,4,5,6,7]].copy()
                    df_dfreq_test = df_dfreq_test2035.copy()
                    df_trein = df_dfreq_trein.iloc[0:semana*7].copy()
                    df_trein = df_trein.iloc[:, [3,4,5,6,7]]
                    atributo = 'dfreq'
                    variacao = '20-35'
                if (z == 3) & (k == 2): #dfreq 40-55
                    df_test  = df_dfreq_test4055.iloc[:, [3,4,5,6,7]].copy()
                    df_dfreq_test = df_dfreq_test4055.copy()
                    df_trein = df_dfreq_trein.iloc[0:semana*7].copy()
                    df_trein = df_trein.iloc[:, [3,4,5,6,7]]
                    atributo = 'dfreq'
                    variacao = '40-55'
                if (z == 3) & (k == 3): #duracao 60-75
                    df_test  = df_dfreq_test6075.iloc[:, [3,4,5,6,7]].copy()
                    df_dfreq_test = df_dfreq_test6075.copy()
                    df_trein = df_dfreq_trein.iloc[0:semana*7].copy()
                    df_trein = df_trein.iloc[:, [3,4,5,6,7]]
                    atributo = 'dfreq'
                    variacao = '60-75'
                if (z == 3) & (k == 4): #duracao 80-95
                    df_test  = df_dfreq_test8095.iloc[:, [3,4,5,6,7]].copy()
                    df_dfreq_test = df_dfreq_test8095.copy()
                    df_trein = df_dfreq_trein.iloc[0:semana*7].copy()
                    df_trein = df_trein.iloc[:, [3,4,5,6,7]]
                    atributo = 'dfreq'
                    variacao = '80-95'   
                if (z == 3) & (k == 5): #duracao 20-95
                    df_test  = df_dfreq_test2095.iloc[:, [3,4,5,6,7]].copy()
                    df_dfreq_test = df_dfreq_test2095.copy()
                    df_trein = df_dfreq_trein.iloc[0:semana*7].copy()
                    df_trein = df_trein.iloc[:, [3,4,5,6,7]]
                    atributo = 'dfreq'
                    variacao = '20-95'                     
                    
                #standarização
                scaler = StandardScaler().fit(df_trein)
                df_trein = scaler.transform(df_trein).copy()
                df_test = scaler.transform(df_test).copy()

                # aplicando o primeiro algoritmo o OSMV
                # fit the model
                if y == 1:
                    clf = svm.OneClassSVM(nu=0.1, kernel='rbf', gamma='scale')
                    algoritmo = 'ocsvm'
                if y == 2:
                    clf = LocalOutlierFactor(n_neighbors=10, novelty=True)
                    algoritmo = 'lof'
                if y == 3:
                    clf = IsolationForest(contamination= 0.01, random_state=1)
                    algoritmo = 'iforest'
                if y == 4:
                    clf = EllipticEnvelope(contamination= 0.01, random_state=0, support_fraction= 0.9)
                    algoritmo = 'rce'

                clf.fit(df_trein)
                y_pred_train = clf.predict(df_trein)
                y_pred_teste = clf.predict(df_test)
                n_error_train = y_pred_train[y_pred_train == -1].size

                # calculando métricas
                if z == 1 : #duracao
                    df_dur_test['predicao'] = y_pred_teste
                    df_dur_test['vp'] = np.where((df_dur_test['outlier'] == -1) & (df_dur_test['predicao'] == -1), 1,0)
                    df_dur_test['vn'] = np.where((df_dur_test['outlier'] == 1) & (df_dur_test['predicao'] == 1), 1,0)
                    df_dur_test['fp'] = np.where((df_dur_test['outlier'] == -1) & (df_dur_test['predicao'] == 1), 1,0)
                    df_dur_test['fn'] = np.where((df_dur_test['outlier'] == 1) & (df_dur_test['predicao'] == -1), 1,0)
                    VP = df_dur_test['vp'].sum()
                    VN = df_dur_test['vn'].sum()
                    FP = df_dur_test['fp'].sum()
                    FN = df_dur_test['fn'].sum()
                if z == 2 : #freq
                    df_freq_test['predicao'] = y_pred_teste
                    df_freq_test['vp'] = np.where((df_freq_test['outlier'] == -1) & (df_freq_test['predicao'] == -1), 1,0)
                    df_freq_test['vn'] = np.where((df_freq_test['outlier'] == 1) & (df_freq_test['predicao'] == 1), 1,0)
                    df_freq_test['fp'] = np.where((df_freq_test['outlier'] == -1) & (df_freq_test['predicao'] == 1), 1,0)
                    df_freq_test['fn'] = np.where((df_freq_test['outlier'] == 1) & (df_freq_test['predicao'] == -1), 1,0)
                    VP = df_freq_test['vp'].sum()
                    VN = df_freq_test['vn'].sum()
                    FP = df_freq_test['fp'].sum()
                    FN = df_freq_test['fn'].sum()                
                if z == 3 : #dfreq
                    df_dfreq_test['predicao'] = y_pred_teste
                    df_dfreq_test['vp'] = np.where((df_dfreq_test['outlier'] == -1) & (df_dfreq_test['predicao'] == -1), 1,0)
                    df_dfreq_test['vn'] = np.where((df_dfreq_test['outlier'] == 1) & (df_dfreq_test['predicao'] == 1), 1,0)
                    df_dfreq_test['fp'] = np.where((df_dfreq_test['outlier'] == -1) & (df_dfreq_test['predicao'] == 1), 1,0)
                    df_dfreq_test['fn'] = np.where((df_dfreq_test['outlier'] == 1) & (df_dfreq_test['predicao'] == -1), 1,0)
                    VP = df_dfreq_test['vp'].sum()
                    VN = df_dfreq_test['vn'].sum()
                    FP = df_dfreq_test['fp'].sum()
                    FN = df_dfreq_test['fn'].sum()                

                erro = (FP+FN)/(VP+VN+FP+FN) #erro
                acuracia =  (VP+VN)/(VP+VN+FP+FN) # accuracy
                precisao = (VP)/(FP+VP) # precision
                sensibilidade = VP/(FN+VP) #recall
                f1escore = 2 * ((precisao * sensibilidade)/(precisao + sensibilidade))
                #armazenando metricas temp
                csemana.append(semana)
                cvariacao.append(variacao)
                cvp.append(VP)
                cvn.append(VN)
                cfp.append(FP)
                cfn.append(FN)
                cacuracia.append(acuracia)
                cprecisao.append(precisao)
                csensibilidade.append(sensibilidade)
                cf1escore.append(f1escore)
                # dentro do for X SEMANAS

            #criando um dataframe a partir das métricas    
            zipped = list(zip(csemana,cvariacao,cvp,cvn,cfp,cfn,cacuracia, cprecisao, csensibilidade, cf1escore))    
            dfmetricas = pd.DataFrame(zipped, columns=['semanas','variacao','vp', 'vn', 'fp', 'fn','acuracia','precisao','sensibilidade','f1score'])
            dfmetricas['algoritmo'] = algoritmo
            dfmetricas['variavel'] = atributo
            dfmetricas['variacao'] = variacao
            dfmetricas= dfmetricas.replace(np.nan,0)
            #print(dfmetricas.head(20))
            #exportando dataframes para datasets

            dfmetricas.to_csv(r'dataseteh/results/armetricas-'+algoritmo+'-'+atributo+'-var-'+variacao+'-trein126.csv', sep=';', index=False, decimal=',')

            #dentro do for Y MODELOS
        #dentro do for Z ATRIBUTOS

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_lof.py:284: UserWarning: n_neighbors (10) is greater than the total number of samples (7). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(
C:\Users\mauri\AppData\Local\Temp\ipykernel_10312\1240160579.py:191: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_10312\1240160579.py:191: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_10312\1240160579.py:191: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_10312\1240160579.py:191: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_lof.py:284: UserWarning: n_neighbors (10) is greater than the total number of samples (7). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:183: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1.503335392546455 > -35.659333173776410). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:183: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1.425951269506993 > -34.494308911534858). You may want to try with a higher value of support_fraction (current value: 0.895).
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_lof.py:284: UserWarning: n_neighbors (10) is greater than the total number of samples (7). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_lof.py:284: UserWarning: n_neighbors (10) is greater than the total number of samples (7). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_lof.py:284: UserWarning: n_neighbors (10) is greater than the total number of samples (7). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(
C:\Users\mauri\AppData\Local\Temp\ipykernel_10312\1240160579.py:192: RuntimeWarning: invalid value encountered in double_scalars
  f1escore = 2 * ((precisao * sensibilidade)/(precisao + sensibilidade))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:183: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1.503335392546455 > -35.659333173776410). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:183: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1.425951269506993 > -34.494308911534858). You may want to try with a higher value of support_fraction (current value: 0.895).
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_lof.py:284: UserWarning: n_neighbors (10) is greater than the total number of samples (7). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_lof.py:284: UserWarning: n_neighbors (10) is greater than the total number of samples (7). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_lof.py:284: UserWarning: n_neighbors (10) is greater than the total number of samples (7). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:183: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1.503335392546455 > -35.659333173776410). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:183: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1.425951269506993 > -34.494308911534858). You may want to try with a higher value of support_fraction (current value: 0.895).
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_lof.py:284: UserWarning: n_neighbors (10) is greater than the total number of samples (7). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_lof.py:284: UserWarning: n_neighbors (10) is greater than the total number of samples (7). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_lof.py:284: UserWarning: n_neighbors (10) is greater than the total number of samples (7). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(
C:\Users\mauri\AppData\Local\Temp\ipykernel_10312\1240160579.py:192: RuntimeWarning: invalid value encountered in double_scalars
  f1escore = 2 * ((precisao * sensibilidade)/(precisao + sensibilidade))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:183: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1.503335392546455 > -35.659333173776410). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:183: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1.425951269506993 > -34.494308911534858). You may want to try with a higher value of support_fraction (current value: 0.895).
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_lof.py:284: UserWarning: n_neighbors (10) is greater than the total number of samples (7). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_lof.py:284: UserWarning: n_neighbors (10) is greater than the total number of samples (7). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_lof.py:284: UserWarning: n_neighbors (10) is greater than the total number of samples (7). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:183: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1.503335392546455 > -35.659333173776410). You may want to try with a higher value of support_fraction (current value: 0.900).
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\covariance\_robust_covariance.py:183: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-1.425951269506993 > -34.494308911534858). You may want to try with a higher value of support_fraction (current value: 0.895).
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_lof.py:284: UserWarning: n_neighbors (10) is greater than the total number of samples (7). n_neighbors will be set to (n_samples - 1) for estimation.
  warnings.warn(

In [13]:
print(dfmetricas.shape)
dfmetricas.head(60)

(18, 12)

,semanas,variacao,vp,vn,fp,fn,acuracia,precisao,sensibilidade,f1score,algoritmo,variavel
0,1,20-95,32,25,3,10,0.814286,0.914286,0.761905,0.831169,rce,dfreq
1,2,20-95,35,32,0,3,0.957143,1.000000,0.921053,0.958904,rce,dfreq
2,3,20-95,35,35,0,0,1.000000,1.000000,1.000000,1.000000,rce,dfreq
3,4,20-95,35,25,0,10,0.857143,1.000000,0.777778,0.875000,rce,dfreq
4,5,20-95,35,32,0,3,0.957143,1.000000,0.921053,0.958904,rce,dfreq
5,6,20-95,35,34,0,1,0.985714,1.000000,0.972222,0.985915,rce,dfreq
6,7,20-95,35,35,0,0,1.000000,1.000000,1.000000,1.000000,rce,dfreq
7,8,20-95,35,34,0,1,0.985714,1.000000,0.972222,0.985915,rce,dfreq
8,9,20-95,35,35,0,0,1.000000,1.000000,1.000000,1.000000,rce,dfreq
9,10,20-95,35,35,0,0,1.000000,1.000000,1.000000,1.000000,rce,dfreq
10,11,20-95,35,35,0,0,1.000000,1.000000,1.000000,1.000000,rce,dfreq
11,12,20-95,35,35,0,0,1.000000,1.000000,1.000000,1.000000,rce,dfreq
12,13,20-95,35,35,0,0,1.000000,1.000000,1.000000,1.000000,rce,dfreq
13,14,20-95,35,35,0,0,1.000000,1.000000,1.000000,1.000000,rce,dfreq
14,15,20-95,35,35,0,0,1.000000,1.000000,1.000000,1.000000,rce,dfreq
15,16,20-95,35,35,0,0,1.000000,1.000000,1.000000,1.000000,rce,dfreq
16,17,20-95,35,35,0,0,1.000000,1.000000,1.000000,1.000000,rce,dfreq
17,18,20-95,35,34,0,1,0.985714,1.000000,0.972222,0.985915,rce,dfreq

In [14]:
print('DONE')

DONE